const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,DIR=process.env.DATA_DIR||path.join(__dirname,'data'),FILE=path.join(DIR,'store.json');
fs.mkdirSync(DIR,{recursive:true});
const games=[['aztec-gold','AZTEC GOLD','REELS','👑'],['dragon-empire','DRAGON EMPIRE','REELS','🐉'],['thunder-temple','THUNDER TEMPLE','REELS','⚡'],['ocean-treasure','OCEAN TREASURE','SPECIAL','🌊'],['desert-king','DESERT KING','REELS','🏜️'],['samurai-fortune','SAMURAI FORTUNE','REELS','⚔️'],['greek-myth','GREEK MYTH','REELS','🏛️'],['volcano-quest','VOLCANO QUEST','SPECIAL','🌋'],['cosmic-gems','COSMIC GEMS','SPECIAL','💎'],['pirate-treasure','PIRATE TREASURE','REELS','🏴‍☠️']].map(x=>({id:x[0],name:x[1],category:x[2],icon:x[3],minBet:1,maxBet:100,betStep:1,scatterNeeded:4,freeSpins:10,payout:{normal:1.5,big:5,mega:20,epic:50},chances:{normal:22,big:8,mega:2.5,epic:.5}}));
let db;try{db=JSON.parse(fs.readFileSync(FILE))}catch{db={users:[],sessions:{},history:[],settings:{signupScore:1000,enabled:true},games};save()}
function save(){fs.writeFileSync(FILE,JSON.stringify(db,null,2))} const id=()=>crypto.randomUUID(), tok=()=>crypto.randomBytes(24).toString('hex'), hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
function sess(req){return db.sessions[req.headers['x-session-token']]};function auth(req,res,next){let s=sess(req);let u=s&&db.users.find(x=>x.id===s.userId);if(!u)return res.status(401).json({error:'LOGIN_REQUIRED'});req.user=u;next()}function adm(req,res,next){let s=sess(req);if(!s?.admin)return res.status(401).json({error:'ADMIN_REQUIRED'});next()};
const pub=u=>({id:u.id,username:u.username,displayName:u.displayName,score:+u.score.toFixed(2)});
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
app.post('/api/register',(req,res)=>{let{username,displayName,password}=req.body||{},un=String(username||'').trim().toLowerCase();if(!/^[a-z0-9_]{3,20}$/.test(un)||String(password||'').length<6)return res.status(400).json({error:'Username 3-20 ตัว และ Password อย่างน้อย 6 ตัว'});if(db.users.some(u=>u.username===un))return res.status(409).json({error:'Username นี้มีอยู่แล้ว'});let u={id:id(),username:un,displayName:String(displayName||un).slice(0,30),password:hash(password),score:+db.settings.signupScore,createdAt:Date.now()};db.users.push(u);let t=tok();db.sessions[t]={userId:u.id};save();res.json({user:pub(u),token:t})});
app.post('/api/login',(req,res)=>{let u=db.users.find(x=>x.username===String(req.body.username||'').trim().toLowerCase());if(!u||u.password!==hash(req.body.password||''))return res.status(401).json({error:'Username หรือ Password ไม่ถูกต้อง'});let t=tok();db.sessions[t]={userId:u.id};save();res.json({user:pub(u),token:t})});
app.post('/api/logout',auth,(req,res)=>{delete db.sessions[req.headers['x-session-token']];save();res.json({ok:true})});app.get('/api/me',auth,(req,res)=>res.json({user:pub(req.user)}));app.get('/api/games',auth,(req,res)=>res.json({games:db.games}));
function pick(g){let r=Math.random()*100,c=g.chances;if(r<c.epic)return'EPIC';if(r<c.epic+c.mega)return'MEGA';if(r<c.epic+c.mega+c.big)return'BIG';if(r<c.epic+c.mega+c.big+c.normal)return'NORMAL';return'NONE'}
app.post('/api/games/:id/play',auth,(req,res)=>{if(!db.settings.enabled)return res.status(403).json({error:'เกมถูกปิด'});let g=db.games.find(x=>x.id===req.params.id);if(!g)return res.status(404).json({error:'GAME_NOT_FOUND'});let cost=Math.min(g.maxBet,Math.max(g.minBet,+req.body.cost||g.minBet));if(req.user.score<cost)return res.status(400).json({error:'SCORE NOT ENOUGH'});let tier=pick(g),m={NONE:0,NORMAL:g.payout.normal,BIG:g.payout.big,MEGA:g.payout.mega,EPIC:g.payout.epic}[tier],reward=+(cost*m).toFixed(2);req.user.score=+(req.user.score-cost+reward).toFixed(2);let scatter=Math.floor(Math.random()*6),free=scatter>=g.scatterNeeded?g.freeSpins:0;db.history.unshift({id:id(),userId:req.user.id,gameId:g.id,cost,reward,tier,scatter,free,at:Date.now()});save();res.json({score:req.user.score,cost,reward,tier,scatter,free})});
app.get('/api/history',auth,(req,res)=>res.json({history:db.history.filter(x=>x.userId===req.user.id).slice(0,50)}));
app.post('/api/admin/login',(req,res)=>{if(String(req.body.username)!==(process.env.ADMIN_USER||'admin')||String(req.body.password)!==(process.env.ADMIN_PASS||'admin123'))return res.status(401).json({error:'ADMIN_LOGIN_FAILED'});let t=tok();db.sessions[t]={admin:true};save();res.json({token:t})});
app.get('/api/admin/overview',adm,(req,res)=>res.json({users:db.users.map(pub),games:db.games,settings:db.settings}));app.patch('/api/admin/settings',adm,(req,res)=>{if(req.body.signupScore!=null)db.settings.signupScore=Math.max(0,+req.body.signupScore||0);if(req.body.enabled!=null)db.settings.enabled=!!req.body.enabled;save();res.json({ok:true})});
app.patch('/api/admin/users/:id',adm,(req,res)=>{let u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'USER_NOT_FOUND'});if(req.body.score!=null)u.score=Math.max(0,+req.body.score||0);save();res.json({user:pub(u)})});
app.patch('/api/admin/games/:id',adm,(req,res)=>{let g=db.games.find(x=>x.id===req.params.id);if(!g)return res.status(404).json({error:'GAME_NOT_FOUND'});for(let k of ['minBet','maxBet','betStep','scatterNeeded','freeSpins'])if(req.body[k]!=null)g[k]=Math.max(0,+req.body[k]);for(let group of ['payout','chances'])if(req.body[group])for(let k of Object.keys(req.body[group]))if(g[group][k]!=null)g[group][k]=Math.max(0,+req.body[group][k]);save();res.json({game:g})});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public/admin.html')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));app.listen(PORT,()=>console.log('NEON ROYALE V8 on '+PORT));
